//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyZilla.BL.BugzillaHttp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyZilla.BL.BugzillaHttp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee: {0} did not match anything..
        /// </summary>
        internal static string ErrAssigneeNotMatch {
            get {
                return ResourceManager.GetString("ErrAssigneeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bug id..
        /// </summary>
        internal static string ErrInvalidBugID {
            get {
                return ResourceManager.GetString("ErrInvalidBugID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error not identified. Please verify the data you modified..
        /// </summary>
        internal static string ErrNotIdentifiedFail {
            get {
                return ResourceManager.GetString("ErrNotIdentifiedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added bug failed..
        /// </summary>
        internal static string MsgInsBugFailed {
            get {
                return ResourceManager.GetString("MsgInsBugFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug {0} was added to the database..
        /// </summary>
        internal static string MsgInsBugSuccessfully {
            get {
                return ResourceManager.GetString("MsgInsBugSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating  bug {0} failed..
        /// </summary>
        internal static string MsgUpdBugFailed {
            get {
                return ResourceManager.GetString("MsgUpdBugFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bug {0} was successfully updated..
        /// </summary>
        internal static string MsgUpdBugSuccessfully {
            get {
                return ResourceManager.GetString("MsgUpdBugSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugs update failed..
        /// </summary>
        internal static string MsgUpdBunchBugsFailed {
            get {
                return ResourceManager.GetString("MsgUpdBunchBugsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugs {0} have been successfully updated..
        /// </summary>
        internal static string MsgUpdBunchBugsSuccessfully {
            get {
                return ResourceManager.GetString("MsgUpdBunchBugsSuccessfully", resourceCulture);
            }
        }
    }
}
