//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyZilla.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyZilla.UI.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new bug ....
        /// </summary>
        internal static string AddBugInProgress {
            get {
                return ResourceManager.GetString("AddBugInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error. Application settings are not loaded..
        /// </summary>
        internal static string AppSettingsObjNotValid {
            get {
                return ResourceManager.GetString("AppSettingsObjNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug #{0} does not exist or you do not have rights to access it!.
        /// </summary>
        internal static string BugIdDoesNotExists {
            get {
                return ResourceManager.GetString("BugIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a valid bug id !.
        /// </summary>
        internal static string BugIDIsNotValid {
            get {
                return ResourceManager.GetString("BugIDIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug {0} does not exist or you do not have rights to access it!.
        /// </summary>
        internal static string BugNotFound {
            get {
                return ResourceManager.GetString("BugNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugzilla column list cookie failed to be generated!.
        /// </summary>
        internal static string BugzillaListCookieFailedToGenerate {
            get {
                return ResourceManager.GetString("BugzillaListCookieFailedToGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete folder &quot;{0}&quot;? All queries and folders within will be deleted too!.
        /// </summary>
        internal static string ConfirmDeleteFolder {
            get {
                return ResourceManager.GetString("ConfirmDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the query &quot;{0}&quot; ?.
        /// </summary>
        internal static string ConfirmDeleteQuery {
            get {
                return ResourceManager.GetString("ConfirmDeleteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to the {0}.
        /// </summary>
        internal static string ConnectionEstablished {
            get {
                return ResourceManager.GetString("ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This connection name is already in use!.
        /// </summary>
        internal static string ConnectionNameAlreadyExists {
            get {
                return ResourceManager.GetString("ConnectionNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By closing this window you will lose any unsaved data! Are you sure you want to continue?.
        /// </summary>
        internal static string ContinueWithoutSavingData {
            get {
                return ResourceManager.GetString("ContinueWithoutSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit bug {0}.
        /// </summary>
        internal static string EditBugTitle {
            get {
                return ResourceManager.GetString("EditBugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string EndOperation {
            get {
                return ResourceManager.GetString("EndOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid value, please..
        /// </summary>
        internal static string EnterValidValue {
            get {
                return ResourceManager.GetString("EnterValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when inserting bug..
        /// </summary>
        internal static string ErrAddBug {
            get {
                return ResourceManager.GetString("ErrAddBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to server [{0}] failed!.
        /// </summary>
        internal static string ErrConnectionToServerFailed {
            get {
                return ResourceManager.GetString("ErrConnectionToServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when loading bug details..
        /// </summary>
        internal static string ErrGetBugDetails {
            get {
                return ResourceManager.GetString("ErrGetBugDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when loading catalogues..
        /// </summary>
        internal static string ErrLoadingCatalogues {
            get {
                return ResourceManager.GetString("ErrLoadingCatalogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in asynchronous operation..
        /// </summary>
        internal static string ErrorAsyncOperation {
            get {
                return ResourceManager.GetString("ErrorAsyncOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when posting file {0}..
        /// </summary>
        internal static string ErrPostFile {
            get {
                return ResourceManager.GetString("ErrPostFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when searching..
        /// </summary>
        internal static string ErrSearching {
            get {
                return ResourceManager.GetString("ErrSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when connecting to {0}..
        /// </summary>
        internal static string ErrTestConnection {
            get {
                return ResourceManager.GetString("ErrTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when editing bug..
        /// </summary>
        internal static string ErrUpdBug {
            get {
                return ResourceManager.GetString("ErrUpdBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when uploading file. {0}{1}.
        /// </summary>
        internal static string ErrUploadFile {
            get {
                return ResourceManager.GetString("ErrUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection ....
        /// </summary>
        internal static string EstablishingConnection {
            get {
                return ResourceManager.GetString("EstablishingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder configured for exporting [{0}] does not exist!
        ///Please change it from the &quot;Tools-&gt;Global settings&quot; menu..
        /// </summary>
        internal static string ExportFolderDoesNotExist {
            get {
                return ResourceManager.GetString("ExportFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export is not possible because current query is in execution!
        ///Please try again after query ends!.
        /// </summary>
        internal static string ExportNotPossible {
            get {
                return ResourceManager.GetString("ExportNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; is not empty!.
        /// </summary>
        internal static string FolderNotEmpty {
            get {
                return ResourceManager.GetString("FolderNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing a folder is required!.
        /// </summary>
        internal static string FolderRequired {
            get {
                return ResourceManager.GetString("FolderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the report is being generated..
        /// </summary>
        internal static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Bugzilla column list cookie is still in progress!.
        /// </summary>
        internal static string GeneratingBugzillaListCookie {
            get {
                return ResourceManager.GetString("GeneratingBugzillaListCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting bugs details completed.
        /// </summary>
        internal static string GettingBulkBugsDetails_Completed {
            get {
                return ResourceManager.GetString("GettingBulkBugsDetails_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting bugs details.
        /// </summary>
        internal static string GettingBulkBugsDetails_Progress {
            get {
                return ResourceManager.GetString("GettingBulkBugsDetails_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize getting bugs details.
        /// </summary>
        internal static string GettingBulkBugsDetails_Start {
            get {
                return ResourceManager.GetString("GettingBulkBugsDetails_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading bug ID# {0} ....
        /// </summary>
        internal static string LoadBugDetails {
            get {
                return ResourceManager.GetString("LoadBugDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading catalogues for &quot;{0}&quot; ....
        /// </summary>
        internal static string LoadCataloguesInProgress {
            get {
                return ResourceManager.GetString("LoadCataloguesInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading component catalogue ....
        /// </summary>
        internal static string LoadComponentCatalogue {
            get {
                return ResourceManager.GetString("LoadComponentCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading default settings ....
        /// </summary>
        internal static string LoadDefaultSettings {
            get {
                return ResourceManager.GetString("LoadDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading predefined folders and queries.
        /// </summary>
        internal static string LoadDefaultTree {
            get {
                return ResourceManager.GetString("LoadDefaultTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading dependent catalogues ....
        /// </summary>
        internal static string LoadDependentCatalogues {
            get {
                return ResourceManager.GetString("LoadDependentCatalogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading hardware catalogue ....
        /// </summary>
        internal static string LoadHardwareCatalogue {
            get {
                return ResourceManager.GetString("LoadHardwareCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading operators catalogue ...
        /// </summary>
        internal static string LoadOperatorsCatalogue {
            get {
                return ResourceManager.GetString("LoadOperatorsCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading operating system catalogue ....
        /// </summary>
        internal static string LoadOsCatalogue {
            get {
                return ResourceManager.GetString("LoadOsCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading priority catalogue ....
        /// </summary>
        internal static string LoadPriorityCatalogue {
            get {
                return ResourceManager.GetString("LoadPriorityCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading product catalogue ....
        /// </summary>
        internal static string LoadProductCatalogue {
            get {
                return ResourceManager.GetString("LoadProductCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading resolution catalogue ....
        /// </summary>
        internal static string LoadResolutionCatalogue {
            get {
                return ResourceManager.GetString("LoadResolutionCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading severity catalogue ....
        /// </summary>
        internal static string LoadSeverityCatalogue {
            get {
                return ResourceManager.GetString("LoadSeverityCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading specific catalogues ....
        /// </summary>
        internal static string LoadSpecificCatalogues {
            get {
                return ResourceManager.GetString("LoadSpecificCatalogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading status catalogue ....
        /// </summary>
        internal static string LoadStatusCatalogue {
            get {
                return ResourceManager.GetString("LoadStatusCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading version catalogue ....
        /// </summary>
        internal static string LoadVersionCatalogue {
            get {
                return ResourceManager.GetString("LoadVersionCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have too many tab pages opened! Please close some of them!.
        /// </summary>
        internal static string MaxNrOfTabsExceeded {
            get {
                return ResourceManager.GetString("MaxNrOfTabsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been modified the current bug. Do you want to save it?.
        /// </summary>
        internal static string MessModifiedBug {
            get {
                return ResourceManager.GetString("MessModifiedBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the modifications?.
        /// </summary>
        internal static string ModifiedData {
            get {
                return ResourceManager.GetString("ModifiedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One attachment is allowed for this connection for a new bug.{0}After saving the bug, you can edit it and attach many files. .
        /// </summary>
        internal static string MsgAttNotAllowed {
            get {
                return ResourceManager.GetString("MsgAttNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving query count for &quot;{0}&quot; ....
        /// </summary>
        internal static string MsgCountBugs {
            get {
                return ResourceManager.GetString("MsgCountBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you don&apos;t want to save your changes?.
        /// </summary>
        internal static string MsgExistModifications {
            get {
                return ResourceManager.GetString("MsgExistModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open {0} bugs. Are you sure of it?.
        /// </summary>
        internal static string MsgOpenBugs {
            get {
                return ResourceManager.GetString("MsgOpenBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New connection.
        /// </summary>
        internal static string NewConnection {
            get {
                return ResourceManager.GetString("NewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New MyZilla version.
        /// </summary>
        internal static string NewVersionCaption {
            get {
                return ResourceManager.GetString("NewVersionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of MyZilla is now available!
        ///Do you want to open the download webpage?.
        /// </summary>
        internal static string NewVersionMessage {
            get {
                return ResourceManager.GetString("NewVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection {0} is not active. .
        /// </summary>
        internal static string NoActiveConnection {
            get {
                return ResourceManager.GetString("NoActiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the selected bugs has a valid status transition!.
        /// </summary>
        internal static string NoBugWithValidStatusTransition {
            get {
                return ResourceManager.GetString("NoBugWithValidStatusTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, define a connection before adding  a user..
        /// </summary>
        internal static string NoCurrentConnection {
            get {
                return ResourceManager.GetString("NoCurrentConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a user..
        /// </summary>
        internal static string NoCurrentUser {
            get {
                return ResourceManager.GetString("NoCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information about the current connection is loaded.{0}Please, verify if the selected user is logged in..
        /// </summary>
        internal static string NoLoadedCatalogues {
            get {
                return ResourceManager.GetString("NoLoadedCatalogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operation..
        /// </summary>
        internal static string NoOperation {
            get {
                return ResourceManager.GetString("NoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value in this field, please..
        /// </summary>
        internal static string NotEmptyField {
            get {
                return ResourceManager.GetString("NotEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bug {0} has not been modified. .
        /// </summary>
        internal static string NotModifiedBug {
            get {
                return ResourceManager.GetString("NotModifiedBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a valid URL..
        /// </summary>
        internal static string NotValidURL {
            get {
                return ResourceManager.GetString("NotValidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented functionality for {0} files..
        /// </summary>
        internal static string OpenFileError {
            get {
                return ResourceManager.GetString("OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query description is required!.
        /// </summary>
        internal static string QueryDescriptionRequired {
            get {
                return ResourceManager.GetString("QueryDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This query is predefined. You are not allowed to delete predefined queries!.
        /// </summary>
        internal static string QueryIsReadOnly {
            get {
                return ResourceManager.GetString("QueryIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query name is required!.
        /// </summary>
        internal static string QueryNameRequired {
            get {
                return ResourceManager.GetString("QueryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query &quot;{0}&quot; was successful saved!.
        /// </summary>
        internal static string QuerySuccessfulSaved {
            get {
                return ResourceManager.GetString("QuerySuccessfulSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current connection, please..
        /// </summary>
        internal static string SaveCurrentConn {
            get {
                return ResourceManager.GetString("SaveCurrentConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current user, please..
        /// </summary>
        internal static string SaveCurrentUser {
            get {
                return ResourceManager.GetString("SaveCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been successfully saved..
        /// </summary>
        internal static string SaveGlSettingsOK {
            get {
                return ResourceManager.GetString("SaveGlSettingsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string SearchInProgress {
            get {
                return ResourceManager.GetString("SearchInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test failed..
        /// </summary>
        internal static string Test_Failed {
            get {
                return ResourceManager.GetString("Test_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test was successful..
        /// </summary>
        internal static string Test_OK {
            get {
                return ResourceManager.GetString("Test_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string TestConnectionInProgress {
            get {
                return ResourceManager.GetString("TestConnectionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings were not tested..
        /// </summary>
        internal static string TestConnectionWarning {
            get {
                return ResourceManager.GetString("TestConnectionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking account name and password .
        /// </summary>
        internal static string TestCredentials {
            get {
                return ResourceManager.GetString("TestCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating bug {0}.
        /// </summary>
        internal static string UpdateBugInProgress {
            get {
                return ResourceManager.GetString("UpdateBugInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bug {0} was successfully updated..
        /// </summary>
        internal static string UpdBugOK {
            get {
                return ResourceManager.GetString("UpdBugOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you define a connection you can introduce users for it.{0}Do you want to add users in the application?.
        /// </summary>
        internal static string WNoUsers {
            get {
                return ResourceManager.GetString("WNoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, test the current connection before saving it..
        /// </summary>
        internal static string WTestConnection {
            get {
                return ResourceManager.GetString("WTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, test the credentials for the current user..
        /// </summary>
        internal static string WTestCredentials {
            get {
                return ResourceManager.GetString("WTestCredentials", resourceCulture);
            }
        }
    }
}
